server:
  port: 8888

security:
  user:
    name: zer0
    password: joseph
  
spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://127.0.0.1/usr/local/reposGit/repoPrueba.git
          username: zer0
          password: overflow